export const metadata = {
  title: "CRM Dashboard Customers",
  description: "Generated by create next app @BLAZERXXI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
